In [ ]:
# untuk ambil dataset lewat google drive
from google.colab import drive

drive.mount('/content/drive/')

Mounted at /content/drive/


In [ ]:
# Library yang akan dipakai
import pandas as pd
import numpy as np
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.metrics import accuracy_score
from sklearn.model_selection import cross_val_score
from sklearn.preprocessing import StandardScaler

In [ ]:
data = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/ML Project/healthcare-dataset-stroke-data.csv")

## Data Processing

In [ ]:
# menampilkan jumlah fitur dan sample
print(data.shape)
data.head()

(5110, 12)


id  gender   age  hypertension  heart_disease ever_married  \
0   9046    Male  67.0             0              1          Yes   
1  51676  Female  61.0             0              0          Yes   
2  31112    Male  80.0             0              1          Yes   
3  60182  Female  49.0             0              0          Yes   
4   1665  Female  79.0             1              0          Yes   

       work_type Residence_type  avg_glucose_level   bmi   smoking_status  \
0        Private          Urban             228.69  36.6  formerly smoked   
1  Self-employed          Rural             202.21   NaN     never smoked   
2        Private          Rural             105.92  32.5     never smoked   
3        Private          Urban             171.23  34.4           smokes   
4  Self-employed          Rural             174.12  24.0     never smoked   

   stroke  
0       1  
1       1  
2       1  
3       1  
4       1

In [ ]:
# Data cleaning
data = data.drop(columns=['id'])
data = data[data['bmi'].notna()]
data = data[data.smoking_status != "Unknown"]
data = data[data.gender != "Other"]

In [ ]:
x = data.drop(columns=['stroke']) # Data Independen
y = data['stroke'] # Data Dependen

In [ ]:
# One Hot Encoding
oneHotEncoding = ColumnTransformer(transformers = [('encoder', OneHotEncoder(), [0,4,5,6,9])], remainder='passthrough')
x = np.array(oneHotEncoding.fit_transform(x))
print(x)

[[  0.     1.     0.   ...   1.   228.69  36.6 ]
 [  0.     1.     0.   ...   1.   105.92  32.5 ]
 [  1.     0.     0.   ...   0.   171.23  34.4 ]
 ...
 [  1.     0.     0.   ...   0.   125.2   40.  ]
 [  1.     0.     0.   ...   0.    82.99  30.6 ]
 [  0.     1.     0.   ...   0.   166.29  25.6 ]]


In [ ]:
# Jumlah fitur dan sample setelah encoding
x.shape

(3425, 19)

In [ ]:
# Pembagian data training dan data test
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2)

In [ ]:
# standard scaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.fit_transform(x_test)

# Training Model

## Without StandardScaler()

In [ ]:
# SVC dengan kernel apapun
svc_rbf = SVC()
svc_rbf.fit(x_train, y_train)
print(accuracy_score(y_test, svc_rbf.predict(x_test)))

0.9416058394160584


In [ ]:
# SVC dengan kernel linear
svc_linear = SVC(kernel = "linear")
svc_linear.fit(x_train, y_train)
print(accuracy_score(y_test, svc_linear.predict(x_test)))

0.9416058394160584


In [ ]:
# SVC dengan kernel polinomial hingga degree = 6
for i in range(6):
  svm_poly = SVC(kernel = "poly", degree = i)
  svm_poly.fit(x_train, y_train)
  print(accuracy_score(y_test, svm_poly.predict(x_test)))

0.9416058394160584
0.9416058394160584
0.9416058394160584
0.9416058394160584
0.9416058394160584
0.9416058394160584


In [ ]:
# mencari nilai cross value pada svc linear
scores = cross_val_score(svc_linear, x, y, cv=10)
scores

array([0.94752187, 0.94752187, 0.94752187, 0.94752187, 0.94752187,
       0.94736842, 0.94736842, 0.94736842, 0.94736842, 0.94736842])

In [ ]:
# menampilkan metrik
from sklearn import metrics
print(metrics.classification_report(y_test, svc_linear.predict(x_test)))

              precision    recall  f1-score   support

           0       0.94      1.00      0.97       645
           1       0.00      0.00      0.00        40

    accuracy                           0.94       685
   macro avg       0.47      0.50      0.48       685
weighted avg       0.89      0.94      0.91       685



/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


## Using StandardScaler()

In [ ]:
svc_rbf = SVC()
svc_rbf.fit(x_train, y_train)
print(accuracy_score(y_test, svc_rbf.predict(x_test)))

0.9416058394160584


In [ ]:
svc_linear = SVC(kernel = "linear")
svc_linear.fit(x_train, y_train)
print(accuracy_score(y_test, svc_linear.predict(x_test)))

0.9416058394160584


In [ ]:
for i in range(6):
  svm_poly = SVC(kernel = "poly", degree = i)
  svm_poly.fit(x_train, y_train)
  print(accuracy_score(y_test, svm_poly.predict(x_test)))

0.9416058394160584
0.9416058394160584
0.9416058394160584
0.9416058394160584
0.9430656934306569
0.9401459854014599


In [ ]:
scores = cross_val_score(svc_linear, x, y, cv=10)
scores

array([0.94752187, 0.94752187, 0.94752187, 0.94752187, 0.94752187,
       0.94736842, 0.94736842, 0.94736842, 0.94736842, 0.94736842])

In [ ]:
from sklearn import metrics
print(metrics.classification_report(y_test, svc_linear.predict(x_test)))

              precision    recall  f1-score   support

           0       0.94      1.00      0.97       645
           1       0.00      0.00      0.00        40

    accuracy                           0.94       685
   macro avg       0.47      0.50      0.48       685
weighted avg       0.89      0.94      0.91       685



/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


## All Sample Using StandardScaler()

In [ ]:
svc_rbf = SVC()
svc_rbf.fit(x, y)
print(accuracy_score(y, svc_rbf.predict(x)))

0.9474452554744526


In [ ]:
svc_linear = SVC(kernel = "linear")
svc_linear.fit(x, y)
print(accuracy_score(y, svc_linear.predict(x)))

0.9474452554744526


In [ ]:
for i in range(6):
  svm_poly = SVC(kernel = "poly", degree = i)
  svm_poly.fit(x, y)
  print(accuracy_score(y, svm_poly.predict(x)))

0.9474452554744526
0.9474452554744526
0.9474452554744526
0.9474452554744526
0.9474452554744526
0.9474452554744526


In [ ]:
scores = cross_val_score(svc_linear, x, y, cv=10)
scores

array([0.94752187, 0.94752187, 0.94752187, 0.94752187, 0.94752187,
       0.94736842, 0.94736842, 0.94736842, 0.94736842, 0.94736842])

In [ ]:
from sklearn import metrics
print(metrics.classification_report(y, svc_linear.predict(x)))

              precision    recall  f1-score   support

           0       0.95      1.00      0.97      3245
           1       0.00      0.00      0.00       180

    accuracy                           0.95      3425
   macro avg       0.47      0.50      0.49      3425
weighted avg       0.90      0.95      0.92      3425



/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
print(metrics.classification_report(y, svm_poly.predict(x)))

              precision    recall  f1-score   support

           0       0.95      1.00      0.97      3245
           1       0.00      0.00      0.00       180

    accuracy                           0.95      3425
   macro avg       0.47      0.50      0.49      3425
weighted avg       0.90      0.95      0.92      3425



/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
